# Generated by Django 5.2.13 on 2026-04-17 19:26
# lab 6: крок 1 - додано міграцію для початкових даних послуг замість fixtures

from django.db import migrations
from django.utils import timezone


def create_initial_services(apps, schema_editor):
    Service = apps.get_model('shop', 'Service')
    if Service.objects.exists():
        return  # Already populated
    services_data = [
        {
            'name': 'Лікування карієсу',
            'description': 'Професійне лікування карієсу з використанням сучасних пломбувальних матеріалів. Гарантуємо довговічність та естетичний вигляд.',
            'price': 500.00,
            'duration': 60,
        },
        {
            'name': 'Протезування зубів',
            'description': 'Виготовлення та встановлення зубних протезів різних типів: від мостів до імплантів. Відновимо вашу посмішку повністю.',
            'price': 2000.00,
            'duration': 120,
        },
        {
            'name': 'Чищення зубів',
            'description': 'Професійне чищення зубів від нальоту та каменю. Ультразвукова чистка та полірування для здоров\'я та красивої посмішки.',
            'price': 300.00,
            'duration': 45,
        },
        {
            'name': 'Виправлення прикусу',
            'description': 'Ортодонтичне лікування для корекції прикусу. Брекети, елайнери та інші сучасні методи для ідеальної посмішки.',
            'price': 1500.00,
            'duration': 30,
        },
        {
            'name': 'Імплантація зубів',
            'description': 'Встановлення зубних імплантів для заміни втрачених зубів. Сучасні матеріали та методи для надійного результату.',
            'price': 3000.00,
            'duration': 90,
        },
        {
            'name': 'Відбілювання зубів',
            'description': 'Професійне відбілювання зубів для яскравої та здорової посмішки. Безпечні методи без шкоди для емалі.',
            'price': 400.00,
            'duration': 60,
        },
    ]
    
    for data in services_data:
        Service.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_service_image'),
    ]

    operations = [
        migrations.RunPython(create_initial_services),
    ]
