# Generated by Django 5.2.13 on 2026-04-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20260417_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='procedures',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='shop.service', verbose_name='Процедури'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Рейтинг'),
        ),
    ]
